# SwiftLint configuration for Stay Tuned
# Documentation: https://realm.github.io/SwiftLint/rule-directory.html

# Paths to include
included:
  - Stay Tuned/Stay Tuned

# Paths to exclude
excluded:
  - Stay Tuned/Stay Tuned.xcodeproj
  - Stay Tuned/Stay TunedUITests
  - "**/.build"

# Enabled rules beyond defaults
opt_in_rules:
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_count
  - empty_string
  - first_where
  - force_unwrapping
  - implicit_return
  - last_where
  - modifier_order
  - overridden_super_call
  - private_action
  - private_outlet
  - sorted_first_last
  - toggle_bool
  - unused_declaration
  - vertical_whitespace_closing_braces

# Disabled rules
disabled_rules:
  - todo  # Allow TODO comments during development
  - line_length  # Can be noisy in SwiftUI with long modifiers
  - type_body_length  # Views can get long
  - file_length  # Some files are legitimately long
  - function_body_length  # Some audio processing functions need to be long
  - cyclomatic_complexity  # Audio algorithms can be complex

# Type name exceptions (Xcode auto-generates names with underscores)
type_name:
  excluded:
    - Stay_TunedApp

# Rule configurations
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - i
    - j
    - x
    - y
    - db
    - hz
    - Hz

nesting:
  type_level:
    warning: 2
  function_level:
    warning: 3

trailing_comma:
  mandatory_comma: true

vertical_whitespace:
  max_empty_lines: 2

force_cast:
  severity: warning

force_try:
  severity: warning

force_unwrapping:
  severity: warning

# Custom rules
custom_rules:
  no_print_statements:
    name: "No Print Statements"
    regex: '^\s*print\s*\('
    message: "Use os_log or remove debug print statements before committing"
    severity: warning
