# SwiftLint configuration for Stay Tuned
# Documentation: https://realm.github.io/SwiftLint/rule-directory.html

# Paths to include
included:
  - Stay Tuned/Stay Tuned

# Paths to exclude
excluded:
  - Stay Tuned/Stay Tuned.xcodeproj
  - Stay Tuned/Stay TunedUITests
  - "**/.build"

# Disabled rules - either too noisy or not applicable
disabled_rules:
  - todo  # Allow TODO comments during development
  - line_length  # Can be noisy in SwiftUI with long modifiers
  - type_body_length  # Views can get long
  - file_length  # Some files are legitimately long
  - function_body_length  # Some audio processing functions need to be long
  - cyclomatic_complexity  # Audio algorithms can be complex
  - trailing_comma  # Would require too many changes to existing code
  - force_unwrapping  # Common in SwiftUI and audio code
  - implicit_return  # Personal preference
  - for_where  # Subjective style preference
  - identifier_name  # Short names like t, r, g, b are common in graphics/audio
  - implicit_optional_initialization  # Explicit nil is fine
  - function_parameter_count  # Some functions need many parameters
  - void_function_in_ternary  # Sometimes readable
  - vertical_whitespace_closing_braces  # Minor style issue
  - redundant_string_enum_value  # Explicit values are more readable
  - unused_closure_parameter  # Sometimes intentional for readability

# Type name exceptions (Xcode auto-generates names with underscores)
type_name:
  excluded:
    - Stay_TunedApp

# Custom rules
custom_rules:
  no_print_statements:
    name: "No Print Statements"
    regex: '^\s*print\s*\('
    message: "Use os_log or remove debug print statements before committing"
    severity: warning  # Warning only, don't fail
