# SwiftLint Configuration for Stay Tuned

included:
  - Stay Tuned/Stay Tuned

excluded:
  - Stay Tuned/Stay Tuned.xcodeproj
  - Stay Tuned/Stay TunedTests
  - Stay Tuned/Stay TunedUITests

# Rules
disabled_rules:
  - trailing_whitespace
  - line_length
  - type_body_length
  - file_length
  - function_body_length
  - cyclomatic_complexity
  - force_cast
  - force_try

opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - fallthrough
  - first_where
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Configurable rules
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - i
    - j
    - n
    - db
    - hz

large_tuple:
  warning: 4
  error: 5

nesting:
  type_level:
    warning: 2
  function_level:
    warning: 3

reporter: "xcode"

